services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - CleanMapDatabase__ConnectionString=mongodb://mongo:27017
      - CleanMapDatabase__DatabaseName=nexora
      - AiServer__Url=http://195.68.215.115:9000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
