apiVersion: v1
kind: ConfigMap
metadata:
  name: cleanmap-config
  labels:
    app: cleanmap-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  CleanMapDatabase__DatabaseName: "nexora"
  CleanMapDatabase__ReportsCollectionName: "reports"
  AiServer__BaseUrl: "http://100.67.162.29:8000"
  Observability__Enabled: "true"
  Observability__ServiceName: "cleanmap-api"
  Observability__OtlpEndpoint: "http://grafana-alloy:4317"
